version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/terraform

hooks:
  BeforeInstall:
    - location: /home/ubuntu/scripts/before_install.sh
      timeout: 300
      runas: root
