name: SonarCloud Scan

on:
  push:
    branches:
      - main          # or your default branch
  pull_request:
    branches:
      - main          # runs on PRs targeting main

jobs:
  sonarcloud:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectKey: Terraform       # Replace with your SonarCloud project key
          organization: callmekaran    # Replace with your SonarCloud org name
          token: ${{ secrets.SONAR_TOKEN }}
