name: SonarCloud Scan

on:
  push:
    branches:
      - main          # or your default branch
  pull_request:
    branches:
      - main          # runs on PRs targeting main

jobs:
  sonarcloud:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        with:
          organization: callmekaran
          projectKey: callmekaran_Terraform
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
